### ISSUE TITLE
[feature] Add "new message(s)" notifications

### ISSUE THREAD

**Issue by albancrommer** [manitou-mail/manitou-mail-ui#1]
**What** : Ubuntu email applications can use an API to push notifications and manitou could integrate nicely to the system using it. It could overall be nice to come with a notification object that could connect with various notification APIs (Growl for OsX comes to mind as well).  

**Context**: I'm pretty new to manitou. While it's a low priority feature, I think it could be interesting as it is pretty much what any end user expects from an email application these days.

**Technically** : Does the code base contain a notification event ? Anything one could hook a plugin to ? I could come with an Ubuntu plugin as long as the bases of notification are available. 

**Reference** : Messaging menu support in Ubuntu https://wiki.ubuntu.com/MessagingMenu#API

**Comment by manitou-mail** [comment]
That would be a nice addition to the user interface.
Technically, manitou already receives a notification from the database when a new mail is imported.
Ideally, it should use [QSystemTrayIcon](http://qt-project.org/doc/qt-4.8/qsystemtrayicon.html) to forward that notification to the desktop.
In the case of OS X, Growl integration would work out of the box with QSystemTrayIcon, according to the docs.

**Comment by manitou-mail** [comment]
Finally closing this issue now that notifications are available on all platforms (File->Preferences->New mail notifications)
