### ISSUE TITLE
Threading view

### ISSUE THREAD

**Issue by rmast** [manitou-mail/manitou-mail-ui#2]
I tried manitou-mail-ui to get the threading-view the way of the printscreen, but I didn't get it. How do I accomplish that? Would it be possible to add a Mozilla-thunderbird-plugin called 'gmail-conversation-view'?

**Comment by manitou-mail** [comment]
The hierarchical display of threads is enabled by the menu entry _Display->Threaded_, which should be set to on by default.
As for plugins, I'm afraid the user interface does not support plugins.

**Comment by rmast** [comment]
Display->Threaded only moves my mailsubjects right by about 3 characters. But no threading of the mails.

I was curious whether Manitou-mail has any collapsing of quoted mails in a thread.

**Comment by rmast** [comment]
I saw some minimal threading now (a pointer with only one message deep in threads of more than 10 messages) 

It falsely assumed the e-mailadres of the configuration-file to be the sender of some mail, so I adapted the config-file.

I tried to flush my database to get my own e-mailadres.

I think somewhere my perl got upgraded. I now get the following message with every manitou-mgr I try to run:

Use of qw(...) as parentheses is deprecated at /usr/share/perl5/Manitou/Schema.pm line 745.

Even an update from perl 5.14.2 to perl 5.16 doesn't seem to solve this perl-issue, so I expect /usr/share/perl5/Manitou/Schema.pm has to be adapted to this newly introduced perl incompatibility.

The buglist of Mozilla Thunderbird and it's gmail-conversation view has more activity.

**Comment by manitou-mail** [comment]
The parent-child relationship in threads comes from the In-Reply-To header matching an existing Message-Id. Some mailers and notably MS-Outlook don't set In-Reply-To.

The Perl message "use of qw(...)" is fixed in development but you may ignore it, it's just a warning.
