### ISSUE TITLE
QString& mail_displayer::htmlize(QString s)

### ISSUE THREAD

**Issue by duncan-grant** [manitou-mail/manitou-mail-ui#7]
In mail_displayer.cpp:

I think it should be
QString mail_displayer::htmlize(QString s)
rather than:
QString& mail_displayer::htmlize(QString s)

It makes my msvc build crash but strangely not the gcc build.

**Comment by manitou-mail** [comment]
I think this signature was intentional, since QString::replace() returns QString& and does an in-place update.
Can you provide the corresponding MSVC error message?

**Comment by duncan-grant** [comment]
The problem I believe (and I'm no expert!) is that the string parameter 's' is being passed-in by value which means a temporary copy is made. So when the function returns a reference it is to the out of scope copy. GCC seems to allow this, msvc doesn't, apparently.

I see 3 solutions:
1) pass by value on input and return, which is not as inefficient as it sounds because of the 'implicit-sharing' magic (http://doc.qt.io/qt-5/implicit-sharing.html)

2) pass by reference on input and return. That requires a small change to 'mail_msg::set_quoted_body(' since htmlize is here applied to a const QString&
from:
`mail_msg::set_quoted_body(const QString& squote, const QString& sprepend, body_format format)
{
  if (format == format_html) {
    QString html = "<html><body>";
    html.append(mail_displayer::htmlize(sprepend));`

to:
`mail_msg::set_quoted_body(const QString& squote, const QString& sprepend, body_format format)
{
  if (format == format_html) {
    QString html = "<html><body>";
    QString sprepend;  // makes a copy ***********************
    html.append(mail_displayer::htmlize(sprepend));`

3) pass by reference and make an explicit copy to a local **static** qstring.

Option 1) seems easiest and safest.

MSVC doesn't give an error message - just an 'AppCrash' when running (doing a reply to sender with html format mail). Debugging fails because Webkit fires various asserts when in debug mode.

**Comment by manitou-mail** [comment]
I agree with your analysis.
Returning a reference to the input is incorrect; the gcc-generated code is probably just lucky not to crash. I'll go for passing by value.
Fixed by commit d780cc78, thanks for the report!
