### ISSUE TITLE
Printing problem on Windows computer

### ISSUE THREAD

**Issue by TLKDev** [manitou-mail/manitou-mail-ui#8]
Hi, thank you for your software.
On my Windows computer, when I try to print a message, nothing happens.
I use **Manitou-Mail version 1.6.0**.
Best regards.

**Comment by manitou-mail** [comment]
Windows systems that don't have Qt installed need `printsupport\windowsprintersupport.dll` in the installation directory for the printer dialog to show up.
That file was lacking in the 1.6.0 installer for Windows, I've added it now.
Reinstalling the client with that installer should solve the problem.

**Comment by manitou-mail** [comment]
Got confirmation that adding the DLL fixes the problem.
